apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: default
  annotations:
    # Redirection automatique HTTP vers HTTPS
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    # Cert-manager génère automatiquement le certificat Let's Encrypt
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - simon-prod.uksouth.cloudapp.azure.com
    secretName: api-gateway-tls-cert
  rules:
  - host: simon-prod.uksouth.cloudapp.azure.com
    http:
      paths:
      # Route spécifique pour l'API d'ingestion (doit être avant /api/v1)
      - path: /api/v1/ingestion
        pathType: Prefix
        backend:
          service:
            name: api-ingestion-service
            port:
              number: 3001
      # Routes API sans strip (car elles ont déjà /api/v1 dans le code)
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: api-gateway-client-service
            port:
              number: 3003
