apiVersion: skaffold/v4beta7
kind: Config

metadata:
  name: api-capteur-dev

build:
  # On active le push vers la registry locale
  local:
    push: true 
  artifacts:
    - image: localhost:5000/api-capteur # Adapte avec l'adresse de ta registry locale si besoin
      # Contexte : Chemin vers le dossier contenant ton code Node.js et ton Dockerfile
      context: ../../APIs/api-capteur 
      custom:
        # Commande pour build avec docker
        buildCommand: |
          docker build -t $IMAGE -t localhost:5000/api-capteur:latest .
          docker push $IMAGE
          docker push localhost:5000/api-capteur:latest
        dependencies:
          paths:
            - src/**/*
            - package.json
            - tsconfig.json # Si tu utilises TypeScript
            - Dockerfile
      
      # Configuration du Hot Reload (File Sync)
      sync:
        manual:
          # On synchronise tout ce qui est dans src local vers /app/src dans le conteneur
          # Adapte '/app' selon le WORKDIR de ton Dockerfile
          - src: 'src/**/*.ts'
            dest: /app
            strip: ''
          - src: 'src/**/*.js'
            dest: /app
            strip: ''
          - src: 'package.json'
            dest: /app/package.json

manifests:
  rawYaml:
    - configmap/*.yaml
    - secret/*.yaml
    - statefulset/*.yaml
    - deployment/*.yaml
    - service/*.yaml

deploy:
  kubectl: {}

# Port forwarding automatique pour accéder à tes services
portForward:
  - resourceType: service
    resourceName: api-capteur-service
    port: 3000 # Le port exposé par ton service Node
    localPort: 3000
  - resourceType: service
    resourceName: postgis
    port: 5432
    localPort: 5432
